package com.mutuals.notification.entity;

public enum NotificationType {
    NEW_FOLLOWER, MUTUAL_CREATED, STREAK_INVITATION, STREAK_STARTED, INTERACTION_PENDING, INTERACTION_CONFIRMED, PROXIMITY_DETECTED, STREAK_AT_RISK, STREAK_BROKEN, STREAK_MILESTONE, SHIELD_RECEIVED, SHIELD_USED, CHALLENGE_ASSIGNED, CHALLENGE_COMPLETED, ACHIEVEMENT_UNLOCKED, ACTIVITY_LIKED, ACTIVITY_COMMENTED, HIGHLIGHT, WRAPPED_READY, SUBSCRIPTION
}
